name: validate-json-schemas
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-adventureworks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: validate-adventureworks
        id: validate-adventureworks
        uses: GrantBirki/json-yaml-validate@v3.3.0
        with:
          comment: "true"
          use_gitignore: "false"
          json_schema: "./AdventureWorks/.json-schemas/products.schema"
          files: "./AdventureWorks/Product.json"

